# Generated by Django 5.1.2 on 2024-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
