# Generated by Django 5.1.2 on 2024-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegho', '0003_contato_dadospessoais_experienciaprofissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
    ]
